#!/usr/bin/env ruby

require_relative '../shared/common.rb'

# Often a branch falls behind master and it needs to be brough uptodate
# so that the branch has all the commits from master.
#
# One way to do that is to do git rebase master. This script makes that
# process much easier by. This script does following things.
#
# - switch to master
# - gets the latest master
# - switch back to the branch
# - git rebase master
# - push the branch to github
#
# Usage :
#
# stand in a branch and execute git_rebase_master
#

def update_master
  execute_cmd 'git checkout master'
  execute_cmd 'git pull'
end

update_master
execute_cmd "git checkout -b #{ARGV.join(' ')}"
execute_cmd "bin/setup"
execute_cmd "bin/server"
